### PR TITLE
Replace travis with github actions, add ActiveAdmin 3 support

### PR DESCRIPTION
**Pull request by oskarpearson**
Based on https://github.com/activeadmin-plugins/active_admin_datetimepicker/blob/master/.github/workflows/ci.yml

Also:
- Add support for ActiveAdmin 3.*
- Change CI so that the models we generate support newer versions of Ransack.
- Fix a bug in the existing injection into author.rb with newer versions of Rails.
- Update to use a much more recent version of packages by default (Rails 7.1.0, ActiveAdmin 3.2.0).
- Use a pinned version of Chrome service in CI, since otherwise we can end up with a non-production version of Chrome that has no matching chromedriver.
- Update chromedriver to automatically install a version that matches Chrome.

### CODE REVIEW

**Comment by oskarpearson** [comment]
CI has passed here https://github.com/oskarpearson/active_admin_scoped_collection_actions/actions/runs/7503993621 - but not on this repo. It seems like github actions might not be enabled on this repo.

The travis-ci status check will also need to be removed

**Comment by oskarpearson** [comment]
@workgena I noticed you've contributed to this repo and to the dateimepicker repo above - any chance you could review this?

**Comment by workgena** [comment]
@oskarpearson Thank you for your contribution. I’ll try to review it, perhaps this weekend.

**Comment by oskarpearson** [comment]
Thought I'd ping you on this @workgena - thanks for any time you spend on it.

**Review by workgena — APPROVED** [review]
Thanks for contribution. And sorry for waiting so long.

**Comment by workgena** [comment]
@oskarpearson Thank you for contribution. New release of a gem is out: [RubyGems active_admin_scoped_collection_actions 1.0.0](https://rubygems.org/gems/active_admin_scoped_collection_actions/versions/1.0.0) it has support for ActiveAdmin 3.x

**Pull request merged**
